apiVersion: v1
kind: Pod
metadata:
  name: exec-pod
  labels:
    app: exec-pod
spec:
  containers:
    - name: myapp-container
      image: alpine
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']