---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-app
  namespace: the-app
spec:
  selector:
    matchLabels:
      app: the-app
  replicas: 2
  template:
    metadata:
      labels:
        app: the-app
    spec:
      containers:
        - name: the-app
          image: catalinbalan/k101-the-app:v1
          ports:
            - containerPort: 31001
          livenessProbe:
            httpGet:
              path: /the-data
              port: 31001
          readinessProbe:
            httpGet:
              path: /the-data
              port: 31001
